### ISSUE TITLE
Problemas a correr

### ISSUE THREAD

**Issue by VascoGarciaCarvalho** [SuperGuerreiro/soundUML#1]
Boa tarde Nuno,

Estou a continuar a tua tese e não sei o que devo fazer para obter o SoundUML_1.0.00.jmdac para por no modelio. Preciso de fazer que mais imports para além do que está aqui no gitHub?

Cumprimentos
Vasco Carvalho

**Comment by SuperGuerreiro** [comment]
Hey Vasco!

Penso que o .jmdac compilado já esteja aqui no projecto, mas tu queres mesmo conseguir compilar o projecto, certo?

Se for o caso, não me recordo assim de cabeça os passos todos, mas penso que o ficheiro era gerado através do maven  e que tudo o que é preciso já esteja aqui no repositório. Se não tens o maven instalado e o setup feito, tens aqui a documentação do modelio sobre como fazer isso:

https://github.com/ModelioOpenSource/Modelio/wiki/Junit_dev_setting_up_dev_env

Depois de teres o maven instalado e importares o projecto para o eclipse, ao clickares com o botão do lado direito por cima do ficheiro "pom.xml", deves ter lá a opção de "run as" e carregas na "5 Maven Install".

![imagem](https://github.com/SuperGuerreiro/soundUML/assets/44029944/f7bb7f68-cb94-447b-a216-1c34efd3a886)

Ele vai te gerar o ficheiro .jmdac para a pasta "target". 

Diz-me se funcionou!

Boa sorte :)

**Comment by VascoGarciaCarvalho** [comment]
Boa tarde Nuno,

Olha já consegui instalar o Maven. Mas ao correr como fizeste apareceu-me este erro.

<img width="1512" alt="Screenshot 2024-05-15 at 17 22 50" src="https://github.com/SuperGuerreiro/soundUML/assets/62077527/34c44b81-fee0-4902-b667-405b6378b48b">

Basicamente diz-me que falta uma classe para conseguir gerar o .jdmac. Sabes o que pode ser.

Desculpa estar a incomodar novamente.

**Comment by SuperGuerreiro** [comment]
Hey Vasco!

Hmm, nunca tive esse problema, mas assim à primeira vista parece-me que possa ser algo relacionado com configuração e versões diferentes das esperadas pelo pom. Verifica se tens as versões todas iguais ao que está dentro do pom e se estás na versão de java correcta. 

Às vezes os repositórios do maven podem ficar corrompidos, também podes tentar limpar a cache dos repositorios (podes só apagar a pasta `.m2/repository` e quando executares o build do maven, ele saca tudo novamente)

O que diz a linha "Failed to execute goal org.modelio:modelio..." ? No print que mandaste não dá para se ver a mensagem toda, se conseguires, manda o log para aqui, sff

Abraço!

**Comment by VascoGarciaCarvalho** [comment]
Boa tarde Nuno,

Que configuração de versões estavas a falar mais especificamente, eu tenho o java 8

Em relação a apaga o .m2/repository já o fiz e não resolveu o problema.

O log diz "Failed to execute goal org.modelio:modelio-maven-plugin:5.1.0.00:module-validation (ModuleValidation)on project soundUML:Execution ModuleValidation of goal org.modelio:modelio-maven-plugin:5.1.0.00:module-validation failed: A required class was missing while executing org.modelio:modelio-maven-plugin:5.1.0.00:module-validation: javax/xml/bind/JAXBException"

Abraço.

**Comment by VascoGarciaCarvalho** [comment]
Nuno boa tarde,

Desculpa estar a chatear novamente, mas eu já instalei o Maven e tudo mais mas ao seguir o tutorial que me enviaste para criar o projeto para o modelio dá um erro. Downloaded[90m from [0mcentral[90m: https://repo.maven.apache.org/maven2/[0mcom/ibm/icu/icu4j/70.1/icu4j-70.1.jar[90m (14 MB at 6.6 MB/s)[0m
[INFO] Generating project in Interactive mode
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.

Isso aconteceu-te?

 Acho que pode ser por isso que depois quando tento correr o o pom.xml  está a dar erro. 

Abraço e desculpa mais uma vez

**Comment by SuperGuerreiro** [comment]
Hey Vasco,

Desculpa não te ter respondido, não tenho tido muito tempo! 

Mas realmente, isso é estranho, não me lembro de ter tido esses problemas, ele falha por causa desses warnings, ou há mais qualquer coisa no log?

Abraço!

**Comment by SuperGuerreiro** [comment]
Já agora, estás a correr que versão do java? O projecto está no jre1.8 (Java 8)

**Comment by VascoGarciaCarvalho** [comment]
hey Nuno,

Eu estou a usar o java 1.8. tenho uma questão, tu para começares o projeto fizeste este tutorial primeiro?https://github.com/ModelioOpenSource/Modelio/wiki/Junit_dev_setting_up_dev_env ou para começar sacas só do  github logo tudo como está. 

desculpa estar a chatear, tu já estás a trabalhar é normal isso do tempo.
obrigado na mesma

**Comment by VascoGarciaCarvalho** [comment]
Hey Nuno, 

Consegui corrigir o erro, ele depois gerou-me um SoundUML-1.0.00.jar na pasta target que tu não tens aqui no projeto, isto aconteceu-te? Para corrigir o erro tive de adicionar a dependecia JAXB dentro do plugins porque senão não estava a funcionar doutra forma. Ele também gera o jdmac, mas para que serve este jar?
Abraço

**Comment by SuperGuerreiro** [comment]
Hey hey, não me recordo de ter tido esse problema, mas ainda bem que conseguiste pôr isso a correr! Se bem me recordo, o .jmdac é o ficheiro que depois tens de importar para o Modelio, para correr o plugin.
